<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>{{url('/sitemapstaticpages.xml')}}</loc>
    </url>
    <url>
        <loc>{{url('/sitemapjobslug.xml')}}</loc>
    </url>
    <url>
        <loc>{{url('/sitemapjobtitle.xml')}}</loc>
    </url>
    <url>
        <loc>{{url('/sitemapjoblocation.xml')}}</loc>
    </url>
    <url>
        <loc>{{url('/sitemapjobtitlelocation.xml')}}</loc>
    </url>
    <url>
        <loc>{{url('/sitemapjobtype.xml')}}</loc>
    </url>
    <url>
        <loc>{{url('/sitemapjobtypelocation.xml')}}</loc>
    </url>
    <url>
        <loc>{{url('/sitemapjobtypetitle.xml')}}</loc>
    </url>
    <url>
        <loc>{{url('/sitemapjobtypetitlelocation.xml')}}</loc>
    </url>
</urlset>
